Car-Ify-1911FSA/Car-Ify-2020

- package-lock.json
- package.json
> Updated package.json for better sequelize and prettier

- client/components/AllProducts.js
- client/components/ProductCard.js
- client/components/SingleProduct.js
- client/store/allProducts.js
- client/store/index.js
- client/store/singleProduct.js
> AllProducts, SingleProduct component, store updated

- server/db/models/PaymentAccount.js
- server/db/models/Payments.js
- server/db/models/index.js
- server/db/models/payment.js
> finished payment and payment_account models

- client/components/AllProducts.js
- client/components/index.js
- client/routes.js
> Update to allProducts component and route created

- client/components/AllProducts.js
- client/components/Cart.js
- client/components/CartItem.js
- client/components/index.js
- client/components/navbar.js
- client/components/sidebar.js
- client/routes.js
- public/style.css
> Initial Cart and CartItem component

- script/seed.js
- server/db/models/product.js
> products seed array added and imageUrl added into products model

- script/seed.js
- server/db/models/index.js
- server/db/models/order.js
> Fixed product table schema

- client/components/sidebar.js
- script/seed.js
- server/db/models/product.js
> Added quantity to products and seeding

- server/api/index.js
- server/api/products.js
- server/api/users.js
> product routes added

- client/components/sidebar.js
- client/store/allProducts.js
- public/style.css
- script/seed.js
> Updated sidebar to prepare for backend data

- client/components/sidebar.js
- script/seed.js
- server/db/models/PaymentAccount.js
- server/db/models/index.js
> Updated paymentAccount table and added Order and PayAct seed data

- client/components/AllProducts.js
> updated AllProduct component to render cars

- server/api/index.js
- server/api/paymentAccounts.js
- server/api/payments.js
> Payment routes

- public/style.css
> Fixed layout for route divs

- server/api/index.js
- server/api/orders.js
> Slava orders and cart

- client/components/AddToCartButton.js
- client/components/ProductCard.js
- client/components/SingleProduct.js
- client/components/sidebar.js
- public/style.css
> Switched SingleProduct to be pure component

- server/api/users.js
- server/db/models/user.js
> Slava user model

- client/components/AddToCartButton.js
- client/components/Cart.js
- client/components/ProductCard.js
- client/components/SingleProduct.js
- client/store/cart.js
- client/store/cartProduct.js
- public/style.css
- server/api/cartProduct.js
> Cart component

- client/components/AddToCartButton.js
- client/components/Cart.js
- client/store/cart.js
- script/seed.js
- server/api/cart.js
- server/api/products.js
> Cart component update and  minor security update

- client/components/AddToCartButton.js
- client/store/cartProduct.js
> local storage (added to cart functionality for guest)

- client/components/AddToCartButton.js
- client/components/navbar.js
- client/components/sidebar.js
- client/components/user-home.js
- client/store/cart.js
> Cart component update

- client/components/user-home.js
- client/store/cart.js
> Cart Status Local

- client/components/AddToCartButton.js
- client/components/user-home.js
> Fixed adding cart at login

- client/components/AddToCartButton.js
- client/components/Cart.js
- client/components/user-home.js
- client/store/cart.js
- client/store/cartProduct.js
- server/api/cartProduct.js
- server/db/models/index.js
> Fixed posting and putting to cart

- client/components/AddToCartButton.js
- client/components/navbar.js
- client/components/sidebar.js
- client/store/cart.js
- public/style.css
- server/api/cart.js
- server/api/cartProduct.js
> Updated security for CartProduct (remove)

- client/components/Cart.js
- client/store/cart.js
- client/store/cartProduct.js
> guest cart view from LS

- client/components/Cart.js
- client/store/user.js
> improved guest Cart

- client/components/AddToCartButton.js
- client/components/Cart.js
- client/components/CartItem.js
- client/components/CheckoutButton.js
- client/components/PaymentAccounts.js
- client/components/PaymentCard.js
- client/components/SingleProduct.js
- client/components/index.js
- client/components/user-home.js
- client/routes.js
- client/store/cart.js
- client/store/cartProduct.js
- public/style.css
- server/api/cart.js
- server/api/cartProduct.js
- server/api/paymentAccounts.js
- server/api/payments.js
- server/api/products.js
> Checkout Progress with Updated Cart Functionality

- client/components/CheckoutButton.js
- client/store/allProducts.js
- public/style.css
- server/api/cart.js
- server/api/products.js
> Updated checkout functionality

- client/components/Cart.js
- client/components/CartItem.js
- public/style.css
> CartItem component update

- client/components/AddToCartButton.js
- client/components/Cart.js
- client/components/CartItem.js
- client/store/cart.js
- client/store/cartProduct.js
- public/style.css
- server/api/cartProduct.js
- server/db/models/cartProduct.js
- server/db/models/index.js
> Updated checkout functionality and guest cart

- client/components/AddToCartButton.js
- client/components/AllProducts.js
- client/components/Cart.js
- client/components/CartItem.js
- client/components/CheckoutButton.js
- client/components/PaymentAccounts.js
- client/components/auth-form.js
- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
- client/store/cartProduct.js
- client/store/user.js
- public/style.css
> Checkout feature for all users

- client/components/auth-form.js
- client/components/user-home.js
- client/store/cartProduct.js
- client/store/user.js
> Attempt to figure out merging 

- client/components/Top3Products.js
- client/components/index.js
- client/components/user-home.js
- client/store/index.js
- client/store/top3Products.js
> Top 3 functionality added

- client/app.js
- client/components/CartIconQTY.js
- client/components/auth-form.js
- client/components/index.js
- client/components/navbar.js
- client/store/cartProduct.js
- client/store/user.js
- public/style.css
> Cart qty plus some fixes in calculations

- client/components/UpdateProfile.js
- client/components/UserProfile.js
- client/components/index.js
- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
- client/store/index.js
- client/store/userProfile.js
- public/style.css
- server/api/users.js
> ugly userProfile with update

- client/components/cart-table.spec.js
^ ------------------- ^
|
+-> Simulate a cart and testing the right amount of rows are shown in the cart table #64
---
> Added new test: cart table view (# of rows)

- client/components/auth-form.js
- client/components/user-home.js
- client/socket.js
- client/store/userProfile.js
- server/api/cartProduct.js
- server/api/user-cart.spec.js
> cleaned up some console.logs

- client/socket.js
> fix: updated socket connection with callback

- client/components/CartItem.js
- public/style.css
> quick update

- server/api/cart.spec.js
> cart test spec is not working

- server/api/payments.spec.js
- server/api/security.js
- server/api/users.spec.js
> payment spec

- server/api/paymentAccounts.spec.js
- server/api/payments.spec.js
> Test paymentAccount routes

- .gitignore
- client/components/cart-table.spec.js
- client/components/user-home.spec.js
- script/seedData.js
- server/api/user-cart.spec.js
- server/db/models/index.js
^-------------------^
|
+-> Able to pull down the Table component but still need the CartItem to render
---
> feat: testing rows in cart table #64

- server/api/payments.spec.js
- server/api/security.js
- server/api/users.js
|
|--------------------------> fixes #72 fix: wrote a payment type in the database
---
> -----------------

- server/api/cart.js
- server/api/cartProduct.js
- server/api/paymentAccounts.js
- server/api/payments.js
- server/api/products.js
> console error and res send clean up

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.md
- client/components/auth-form.js
- client/components/index.js
- client/components/navbar.js
- client/history.js
- client/index.js
- client/store/user.spec.js
- script/encrypt-heroku-auth-token.js
- script/seed.spec.js
- server/auth/google.js
- server/db/db.js
- server/db/index.js
- server/db/models/payment.js
- server/db/models/user.spec.js
- server/socket/index.js
- webpack.config.js
> Applied prettier to all files

- server/api/security.js
> security.js is cleaned up

- client/components/PaymentAccountForm.js
- client/components/PaymentAccounts.js
- client/store/paymentAccounts.js
- server/api/cart.js
> payment account form is hard coded

- client/components/auth-form.js
- client/components/navbar.js
- client/components/user-home.js
- client/store/cartProduct.js
- client/store/user.js
- client/store/user.spec.js
- server/api/cart.js
- server/api/security.js
- server/auth/index.js
> Merging Cart functionality (both logging-in and signing-up)

- client/components/PaymentAccounts.js
- client/components/PaymentForm.js
- client/components/cart/Cart.js
- client/components/index.js
- client/store/index.js
- client/store/paymentOptions.js
- server/api/products.spec.js
> Slava guest checkout

- client/components/cart/Cart.js
- client/components/navbar.js
> Fixing cart qty item refresh

- client/components/AddToCartButton.js
- client/components/AllProducts.js
- client/components/ProductCard.js
- client/components/Top3Products.js
- client/components/admin/AdminHome.js
- client/components/cart/CartIconQTY.js
- client/components/navbar.js
- client/store/cartProduct.js
- public/style.css
> Fixed cart item quantity display in navbar

- client/components/cart/CheckoutButton.js
> stripe is fake working

- client/components/PaymentAccounts.js
- client/components/PaymentForm.js
- client/components/cart/Cart.js
- client/components/cart/CartIconQTY.js
- client/components/cart/CheckoutButton.js
- client/store/cartProduct.js
- public/style.css
- server/auth/index.js
> Updated checkout process for guest and user

- client/components/cart/CheckoutButton.js
- public/style.css
> Clean up some code and formatting

- client/components/OrderHistory.js
- client/components/admin/AddNewProductForm.js
- client/components/admin/AdminHome.js
- client/components/admin/ListOfAllProducts.js
- package-lock.json
- package.json
- public/style.css
- server/api/products.js
- server/db/models/product.js
> Add New Prod Functionality plus other changes

- public/style.css
> added top for sidebar

- public/style.css
- script/seedData.js
- server/api/security.js
> final edits

- client/components/OrderHistory.js
- client/components/RecentOrderHistory.js
- public/style.css
- script/seedData.js
> loading problem fixed

- server/api/security.js
> minor edit

- client/components/PaymentCard.js
- client/components/Top3Products.js
- client/components/auth-form.js
- client/components/cart/Cart.js
- client/components/cart/CartItem.js
- client/components/cart/TableCart.js
- client/components/sidebar.js
- public/style.css
- script/seedData.js
> Css time - james

- README.md
> readme update header
